version: '3.1'

services:

  mongo:
    image: mongo
    container_name: db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  
  web:
    build: .
    ports:
      - "80:80"
    environment:
      CONNECTION_STRING: "mongodb://root:example@db:27017/"